ozemacs support
git-svn-id: https://gforge.info.ucl.ac.be/svn/mozart@374 ada56829-ad1f-0410-b00f-83cda6628aec

diff --git a/trunk/mozart/share/bin/oz b/trunk/mozart/share/bin/oz
--- a/trunk/mozart/share/bin/oz
+++ b/trunk/mozart/share/bin/oz
@@ -71,49 +71,57 @@ fi
 
 cmd=`basename $howcalled`
 
+# where is Emacs?
+if [ ${OZEMACS-0} = 0 ]; then
+	   
+  if [ -f ${OZHOME}/ozemacs/bin/$OZPLATFORM/emacs ]; then
+
+    OZEMACS=${OZHOME}/ozemacs/bin/$OZPLATFORM/emacs
+    EHOME=$OZHOME/ozemacs
+    EMACSLOADPATH=$EHOME/common/lisp:$EHOME/common/site-lisp
+    EMACSDATA=$EHOME/common/data
+    EMACSDOC=$EMACSDATA
+    INFOPATH=$EHOME/info
+    EMACSLOCKDIR=$EHOME/lock/
+    EMACSPATH=$EHOME/bin/$OZPLATFORM/etc
+    export EMACSLOADPATH EMACSDATA EMACSDOC
+    export INFOPATH EMACSLOCKDIR EMACSPATH
+
+  else
+
+     IFS="${IFS=   }"; saveifs="$IFS"; IFS="$IFS:"
+     for name in emacs lemacs; do
+       for dir in $PATH; do
+	 test -z "$dir" && dir=.
+    	 if test -f $dir/$name; then
+      	   # Not all systems have dirname.
+           OZEMACS=$dir/$name
+      	   break 2
+	 fi
+       done
+     done
+     IFS="$saveifs"
+     if [ ${OZEMACS-0} = 0 ]; then
+	echo "Cannot find emacs" 1>&2
+	echo "Try setting environment variable OZEMACS" 1>&2
+	exit 1
+     fi
+  fi
+fi
+
+export OZEMACS
+
+
 case "$cmd" in
 
    oz) 
-	# where is Emacs?
-	if [ ${OZEMACS-0} = 0 ]; then
-	   
-	   if [ -f ${OZHOME}/ozemacs/bin/$OZPLATFORM/emacs ]; then
-
-	      OZEMACS=${OZHOME}/ozemacs/bin/$OZPLATFORM/emacs
-	      EHOME=$OZHOME/ozemacs
-	      EMACSLOADPATH=$EHOME/common/lisp:$EHOME/common/site-lisp
-	      EMACSDATA=$EHOME/common/data
-	      EMACSDOC=$EMACSDATA
-	      INFOPATH=$EHOME/info
-	      EMACSLOCKDIR=$EHOME/lock/
-	      EMACSPATH=$EHOME/bin/$OZPLATFORM/etc
-	      export EMACSLOADPATH EMACSDATA EMACSDOC
-	      export INFOPATH EMACSLOCKDIR EMACSPATH
-
-	  else
-
-	     IFS="${IFS=   }"; saveifs="$IFS"; IFS="$IFS:"
-             for name in emacs lemacs; do
-	       for dir in $PATH; do
-		 test -z "$dir" && dir=.
-	    	 if test -f $dir/$name; then
-	      	   # Not all systems have dirname.
-	           OZEMACS=$dir/$name
-	      	   break 2
-		 fi
-	       done
-             done
-	     IFS="$saveifs"
-	     if [ ${OZEMACS-0} = 0 ]; then
-		echo "Cannot find emacs" 1>&2
-		echo "Try setting environment variable OZEMACS" 1>&2
-		exit 1
-	     fi
-	  fi
-	fi
         echo "Using emacs '${OZEMACS}'"
 
 	$OZEMACS -l $OZHOME/lib/elisp/ozstartup.el $@ &
+   ;;
+
+   ozemacs) 
+	$OZEMACS $@
    ;;
 
    oz.compiler)
