handle freebsd
git-svn-id: https://gforge.info.ucl.ac.be/svn/mozart@3405 ada56829-ad1f-0410-b00f-83cda6628aec

diff --git a/trunk/mozart/share/bin/ozplatform b/trunk/mozart/share/bin/ozplatform
--- a/trunk/mozart/share/bin/ozplatform
+++ b/trunk/mozart/share/bin/ozplatform
@@ -1,6 +1,12 @@
 #!/bin/sh
 # determine machine architecture and OS version
-system="`/bin/uname -m` `/bin/uname -s` `/bin/uname -r`"
+
+if [ -x /bin/uname ]; then UNAME=/bin/uname
+elif [ -x /usr/bin/uname ]; then UNAME=/usr/bin/uname
+else echo "Cannot find uname" 1>&2 ; exit 1
+fi
+
+system="`$UNAME -m` `$UNAME -s` `$UNAME -r`"
 
 case $system in
    sun4*\ SunOS\ 4.1*)	OZARCH=sunos-sparc
@@ -20,6 +26,9 @@ case $system in
    *AIX*)	        OZARCH=aix3-rs6000
    ;;
    *alpha*OSF1*)        OZARCH=osf1-alpha
+   ;;
+   *i386*FreeBSD*)      OZARCH=freebsd-i486
+		        OZARCH=linux-i486
    ;;
    *)  echo "Cannot determine machine type and OS version" 1>&2 ; exit 1
 esac
