Merged from trunk
git-svn-id: https://gforge.info.ucl.ac.be/svn/mozart@15221 ada56829-ad1f-0410-b00f-83cda6628aec

diff --git a/contrib/gtk/configure b/contrib/gtk/configure
--- a/contrib/gtk/configure
+++ b/contrib/gtk/configure
@@ -1538,41 +1538,19 @@ else
 fi
 
     if test "${GXX}" = yes; then
-      if oz_tmp=`$CXX -dumpversion 2>/dev/null` || oz_tmp=`$CXX --version 2>/dev/null`; then
+      if oz_tmp=`$CXX --version 2>/dev/null`; then
         if expr "$oz_tmp" : egcs >/dev/null; then
-          echo "configure: warning: dont know how to check egcs version, assuming ok" 1>&2
-	else
-	  
-  echo $ac_n "checking $CXX version is at least 2.7""... $ac_c" 1>&6
-echo "configure:1548: checking $CXX version is at least 2.7" >&5
-  oz_tmp_ok=no
-  if oz_tmp_version1=`$CXX -dumpversion || $CXX --version 2>/dev/null`; then
-    # first we try to locate the string "version"
-    oz_tmp_version2=`echo "${oz_tmp_version1}" | tr '\012' ' '`
+          :
 
-    oz_tmp_version=`expr "${oz_tmp_version2}" : '.*version \([0-9._-]*\)'`
-    # if that failed: we look at the end of the first line
-    if test -z "$oz_tmp_version"; then
-      oz_tmp_IFS="$IFS"
-      IFS='
-'
-      for oz_tmp_version3 in ${oz_tmp_version1}; do
-        oz_tmp_version=`expr "${oz_tmp_version3}" : '.* \([0-9._-]*\)$'`
-	# else try to match the entire first line
-	if test -z "$oz_tmp_version"; then
-	  oz_tmp_version=`expr "${oz_tmp_version3}" : '\([0-9._-]*\)$'`
-	fi
-	break
-      done
-      IFS="$oz_tmp_IFS"
-    fi
+        elif oz_tmp=`expr "$oz_tmp" : '\([0-9.]*\)'`; then
 
-    if test -n "$oz_tmp_version"; then
-      
-  oz_tmp_got="$oz_tmp_version"
+          echo $ac_n "checking $CXX version is at least 2.7""... $ac_c" 1>&6
+echo "configure:1549: checking $CXX version is at least 2.7" >&5
+          
+  oz_tmp_got="$oz_tmp"
   oz_tmp_want="2.7"
   oz_tmp_IFS="$IFS"
-  IFS="$IFS._-"
+  IFS="$IFS._"
   set $oz_tmp_got DONE
   oz_tmp__ok=yes
   for oz_tmp_cur in $oz_tmp_want; do
@@ -1588,18 +1566,10 @@ echo "configure:1548: checking $CXX version is at least 2.7" >&5
   done
   IFS=$oz_tmp_IFS
   oz_tmp_ok=$oz_tmp__ok
-    fi
-  fi
-  if test -z "$oz_tmp_version"; then
-    echo "$ac_t""no (cannot find version)" 1>&6
-  elif test $oz_tmp_ok = no; then
-    echo "$ac_t""no" 1>&6
-  else
-    echo "$ac_t""yes ($oz_tmp_version)" 1>&6
-  fi
-	  if test "$oz_tmp_ok" = no; then
+          echo "$ac_t""$oz_tmp_ok" 1>&6
+          if test "$oz_tmp_ok" = no; then
             { echo "configure: error: 
-configure found the GNU C++ compiler $CXX version $oz_tmp_version
+configure found the GNU C++ compiler $CXX version $oz_tmp
 but version 2.7 or higher is required to build the
 system.  It can be retrieved from:
 
@@ -1615,6 +1585,8 @@ You may find a mirror archive closer to you by consulting:
 	http://www.gnu.org/order/ftp.html
 " 1>&2; exit 1; }
           fi
+        else
+          echo "configure: warning: Could not check $CXX version, assuming ok" 1>&2
         fi
       else
         echo "configure: warning: Could not check $CXX version, assuming ok" 1>&2
@@ -1635,7 +1607,7 @@ You may find a mirror archive closer to you by consulting:
 	    for ozm_opt in $oz_for
 	    do
 		echo $ac_n "checking c++ compiler option $ozm_opt""... $ac_c" 1>&6
-echo "configure:1639: checking c++ compiler option $ozm_opt" >&5
+echo "configure:1611: checking c++ compiler option $ozm_opt" >&5
 		ozm_ropt=`echo $ozm_opt | sed -e 's/[^a-zA-Z0-9_]/_/g'`
 		if eval "test \"`echo '$''{'oz_cv_gxxopt_$ozm_ropt'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -1666,7 +1638,7 @@ fi
     ;;
     esac
     echo $ac_n "checking how to run the C++ preprocessor""... $ac_c" 1>&6
-echo "configure:1670: checking how to run the C++ preprocessor" >&5
+echo "configure:1642: checking how to run the C++ preprocessor" >&5
 if test -z "$CXXCPP"; then
 if eval "test \"`echo '$''{'ac_cv_prog_CXXCPP'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -1679,12 +1651,12 @@ ac_link='${CXX-g++} -o conftest${ac_exeext} $CXXFLAGS $CPPFLAGS $LDFLAGS conftes
 cross_compiling=$ac_cv_prog_cxx_cross
   CXXCPP="${CXX-g++} -E"
   cat > conftest.$ac_ext <<EOF
-#line 1683 "configure"
+#line 1655 "configure"
 #include "confdefs.h"
 #include <stdlib.h>
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:1688: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:1660: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
   :
@@ -1716,23 +1688,23 @@ echo "$ac_t""$CXXCPP" 1>&6
   else
     
   echo $ac_n "checking for C++ compiler""... $ac_c" 1>&6
-echo "configure:1720: checking for C++ compiler" >&5
+echo "configure:1692: checking for C++ compiler" >&5
   CXX=$oz_cv_CXX
   echo "$ac_t""(cached) $CXX" 1>&6
     
   echo $ac_n "checking whether we are using GNU C++""... $ac_c" 1>&6
-echo "configure:1725: checking whether we are using GNU C++" >&5
+echo "configure:1697: checking whether we are using GNU C++" >&5
   GXX=$oz_cv_GXX
   echo "$ac_t""(cached) $GXX" 1>&6
     
   echo $ac_n "checking for C++ preprocessor""... $ac_c" 1>&6
-echo "configure:1730: checking for C++ preprocessor" >&5
+echo "configure:1702: checking for C++ preprocessor" >&5
   CXXCPP=$oz_cv_CXXCPP
   echo "$ac_t""(cached) $CXXCPP" 1>&6
     if test "${CXXFLAGS+set}" != set; then
       
   echo $ac_n "checking for default CXXFLAGS""... $ac_c" 1>&6
-echo "configure:1736: checking for default CXXFLAGS" >&5
+echo "configure:1708: checking for default CXXFLAGS" >&5
   CFLAGS=$oz_cv_CFLAGS
   echo "$ac_t""(cached) $CFLAGS" 1>&6
     fi
@@ -1761,7 +1733,7 @@ cross_compiling=$ac_cv_prog_cxx_cross
     # Extract the first word of "ozengine", so it can be a program name with args.
 set dummy ozengine; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:1765: checking for $ac_word" >&5
+echo "configure:1737: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_OZENGINE'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1809,7 +1781,7 @@ fi
     # Extract the first word of "flex", so it can be a program name with args.
 set dummy flex; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:1813: checking for $ac_word" >&5
+echo "configure:1785: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_prog_LEX'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1843,7 +1815,7 @@ then
   *) ac_lib=l ;;
   esac
   echo $ac_n "checking for yywrap in -l$ac_lib""... $ac_c" 1>&6
-echo "configure:1847: checking for yywrap in -l$ac_lib" >&5
+echo "configure:1819: checking for yywrap in -l$ac_lib" >&5
 ac_lib_var=`echo $ac_lib'_'yywrap | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -1851,7 +1823,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-l$ac_lib  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 1855 "configure"
+#line 1827 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 #ifdef __cplusplus
@@ -1865,7 +1837,7 @@ int main() {
 yywrap()
 ; return 0; }
 EOF
-if { (eval echo configure:1869: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:1841: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -1899,35 +1871,18 @@ fi
     else
       
   echo $ac_n "checking $LEX version is at least 2.5.3""... $ac_c" 1>&6
-echo "configure:1903: checking $LEX version is at least 2.5.3" >&5
+echo "configure:1875: checking $LEX version is at least 2.5.3" >&5
   oz_tmp_ok=no
-  if oz_tmp_version1=`$LEX --version 2>/dev/null`; then
-    # first we try to locate the string "version"
-    oz_tmp_version2=`echo "${oz_tmp_version1}" | tr '\012' ' '`
+  if oz_tmp_version=`$LEX --version 2>/dev/null | tr '\012' ' '`; then
 
-    oz_tmp_version=`expr "${oz_tmp_version2}" : '.*version \([0-9._-]*\)'`
-    # if that failed: we look at the end of the first line
-    if test -z "$oz_tmp_version"; then
-      oz_tmp_IFS="$IFS"
-      IFS='
-'
-      for oz_tmp_version3 in ${oz_tmp_version1}; do
-        oz_tmp_version=`expr "${oz_tmp_version3}" : '.* \([0-9._-]*\)$'`
-	# else try to match the entire first line
-	if test -z "$oz_tmp_version"; then
-	  oz_tmp_version=`expr "${oz_tmp_version3}" : '\([0-9._-]*\)$'`
-	fi
-	break
-      done
-      IFS="$oz_tmp_IFS"
-    fi
+    oz_tmp_version=`expr "$oz_tmp_version" : '.*version \([0-9._]*\)'`
 
     if test -n "$oz_tmp_version"; then
       
   oz_tmp_got="$oz_tmp_version"
   oz_tmp_want="2.5.3"
   oz_tmp_IFS="$IFS"
-  IFS="$IFS._-"
+  IFS="$IFS._"
   set $oz_tmp_got DONE
   oz_tmp__ok=yes
   for oz_tmp_cur in $oz_tmp_want; do
@@ -1947,10 +1902,8 @@ echo "configure:1903: checking $LEX version is at least 2.5.3" >&5
   fi
   if test -z "$oz_tmp_version"; then
     echo "$ac_t""no (cannot find version)" 1>&6
-  elif test $oz_tmp_ok = no; then
-    echo "$ac_t""no" 1>&6
   else
-    echo "$ac_t""yes ($oz_tmp_version)" 1>&6
+    echo "$ac_t""$oz_tmp_ok" 1>&6
   fi
     fi
     if test "$oz_tmp_ok" = yes; then
@@ -1980,7 +1933,7 @@ You may find a mirror archive closer to you by consulting:
   else
     
   echo $ac_n "checking for GNU flex""... $ac_c" 1>&6
-echo "configure:1984: checking for GNU flex" >&5
+echo "configure:1937: checking for GNU flex" >&5
   LEX=$oz_cv_LEX
   echo "$ac_t""(cached) $LEX" 1>&6
   fi
@@ -1994,7 +1947,7 @@ do
 # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:1998: checking for $ac_word" >&5
+echo "configure:1951: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_prog_YACC'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -2037,35 +1990,18 @@ test -n "$YACC" || YACC="yacc"
     else
       
   echo $ac_n "checking $YACC version is at least 1.25""... $ac_c" 1>&6
-echo "configure:2041: checking $YACC version is at least 1.25" >&5
+echo "configure:1994: checking $YACC version is at least 1.25" >&5
   oz_tmp_ok=no
-  if oz_tmp_version1=`$YACC --version 2>/dev/null`; then
-    # first we try to locate the string "version"
-    oz_tmp_version2=`echo "${oz_tmp_version1}" | tr '\012' ' '`
+  if oz_tmp_version=`$YACC --version 2>/dev/null | tr '\012' ' '`; then
 
-    oz_tmp_version=`expr "${oz_tmp_version2}" : '.*version \([0-9._-]*\)'`
-    # if that failed: we look at the end of the first line
-    if test -z "$oz_tmp_version"; then
-      oz_tmp_IFS="$IFS"
-      IFS='
-'
-      for oz_tmp_version3 in ${oz_tmp_version1}; do
-        oz_tmp_version=`expr "${oz_tmp_version3}" : '.* \([0-9._-]*\)$'`
-	# else try to match the entire first line
-	if test -z "$oz_tmp_version"; then
-	  oz_tmp_version=`expr "${oz_tmp_version3}" : '\([0-9._-]*\)$'`
-	fi
-	break
-      done
-      IFS="$oz_tmp_IFS"
-    fi
+    oz_tmp_version=`expr "$oz_tmp_version" : '.*version \([0-9._]*\)'`
 
     if test -n "$oz_tmp_version"; then
       
   oz_tmp_got="$oz_tmp_version"
   oz_tmp_want="1.25"
   oz_tmp_IFS="$IFS"
-  IFS="$IFS._-"
+  IFS="$IFS._"
   set $oz_tmp_got DONE
   oz_tmp__ok=yes
   for oz_tmp_cur in $oz_tmp_want; do
@@ -2085,10 +2021,8 @@ echo "configure:2041: checking $YACC version is at least 1.25" >&5
   fi
   if test -z "$oz_tmp_version"; then
     echo "$ac_t""no (cannot find version)" 1>&6
-  elif test $oz_tmp_ok = no; then
-    echo "$ac_t""no" 1>&6
   else
-    echo "$ac_t""yes ($oz_tmp_version)" 1>&6
+    echo "$ac_t""$oz_tmp_ok" 1>&6
   fi
     fi
     if test "$oz_tmp_ok" = yes; then
@@ -2119,7 +2053,7 @@ You may find a mirror archive closer to you by consulting:
   else
     
   echo $ac_n "checking for GNU bison""... $ac_c" 1>&6
-echo "configure:2123: checking for GNU bison" >&5
+echo "configure:2057: checking for GNU bison" >&5
   YACC=$oz_cv_YACC
   echo "$ac_t""(cached) $YACC" 1>&6
   fi
@@ -2130,7 +2064,7 @@ echo "configure:2123: checking for GNU bison" >&5
 # Extract the first word of "cpp", so it can be a program name with args.
 set dummy cpp; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:2134: checking for $ac_word" >&5
+echo "configure:2068: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_CPP'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -2171,7 +2105,7 @@ fi
 # Extract the first word of "gtk-config", so it can be a program name with args.
 set dummy gtk-config; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:2175: checking for $ac_word" >&5
+echo "configure:2109: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_GTKCONFIG'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -2208,7 +2142,7 @@ if test -z $GTKCONFIG; then
 fi
 
 echo $ac_n "checking for GTK+ version""... $ac_c" 1>&6
-echo "configure:2212: checking for GTK+ version" >&5
+echo "configure:2146: checking for GTK+ version" >&5
 GTKVERSION=`$GTKCONFIG --version`
 case $GTKVERSION in
   1.2.*)
@@ -2221,7 +2155,7 @@ case $GTKVERSION in
 esac
 
 echo $ac_n "checking for --with-gtk-canvas-dir""... $ac_c" 1>&6
-echo "configure:2225: checking for --with-gtk-canvas-dir" >&5
+echo "configure:2159: checking for --with-gtk-canvas-dir" >&5
 # Check whether --with-gtk_canvas_dir or --without-gtk_canvas_dir was given.
 if test "${with_gtk_canvas_dir+set}" = set; then
   withval="$with_gtk_canvas_dir"
