Bug fix
git-svn-id: https://gforge.info.ucl.ac.be/svn/mozart@5689 ada56829-ad1f-0410-b00f-83cda6628aec

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -576,11 +576,15 @@ echo "$ac_t""$host" 1>&6
 	if test ! -r $TOPDIR/OZVERSION
 	then
 	    TOPDIR=$srcdir/..
-	fi
+	    if test ! -r $TOPDIR/OZVERSION
+	    then
+	       TOPDIR=$srcdir/../..
+	    fi 
+       fi
     fi
     if test ! -r $TOPDIR/OZVERSION
     then
-	{ echo "configure: error: can't find TOPDIR" 1>&2; exit 1; }
+	{ echo "configure: error: can't find TOPDIR in $TOPDIR" 1>&2; exit 1; }
     fi
     
     oz_topdira=`cd $TOPDIR; pwd`
@@ -597,7 +601,7 @@ echo "$ac_t""$host" 1>&6
 # SVR4 /usr/ucb/install, which tries to use the nonexistent group "staff"
 # ./install, which can be erroneously created by make from ./install.sh.
 echo $ac_n "checking for a BSD compatible install""... $ac_c" 1>&6
-echo "configure:601: checking for a BSD compatible install" >&5
+echo "configure:605: checking for a BSD compatible install" >&5
 if test -z "$INSTALL"; then
 if eval "test \"`echo '$''{'ac_cv_path_install'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -653,7 +657,7 @@ test -z "$INSTALL_DATA" && INSTALL_DATA='${INSTALL} -m 644'
     # Extract the first word of "mkinstalldirs", so it can be a program name with args.
 set dummy mkinstalldirs; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:657: checking for $ac_word" >&5
+echo "configure:661: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_MKINSTALLDIRS'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -663,7 +667,7 @@ else
   ;;
   *)
   IFS="${IFS= 	}"; ac_save_ifs="$IFS"; IFS="${IFS}:"
-  for ac_dir in $PATH:$oz_topdira/bin:$oz_topdira$ac_dummy; do
+  for ac_dir in $PATH:$oz_topdira/share/bin:$oz_topdira$ac_dummy; do
     test -z "$ac_dir" && ac_dir=.
     if test -f $ac_dir/$ac_word; then
       ac_cv_path_MKINSTALLDIRS="$ac_dir/$ac_word"
@@ -683,7 +687,8 @@ fi
 
     if test ! -n "$MKINSTALLDIRS"
     then
-	{ echo "configure: error: required program \"mkinstalldirs\" not found" 1>&2; exit 1; }
+	MKINSTALLDIRS=undefined
+	
     fi
     
 
