*) GFS declaration fixed *) DECLARE_INT_SET3
git-svn-id: https://gforge.info.ucl.ac.be/svn/mozart@16979 ada56829-ad1f-0410-b00f-83cda6628aec

diff --git a/branches/mozart-gecode/mozart/doc/configure b/branches/mozart-gecode/mozart/doc/configure
--- a/branches/mozart-gecode/mozart/doc/configure
+++ b/branches/mozart-gecode/mozart/doc/configure
@@ -1554,8 +1554,134 @@ fi
 
 
 
+
+for ac_prog in latex2png
+do
+# Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
+echo "configure:1564: checking for $ac_word" >&5
+if eval "test \"`echo '$''{'ac_cv_prog_latex2png'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  if test -n "$latex2png"; then
+  ac_cv_prog_latex2png="$latex2png" # Let the user override the test.
+else
+  IFS="${IFS= 	}"; ac_save_ifs="$IFS"; IFS=":"
+  ac_dummy="$PATH"
+  for ac_dir in $ac_dummy; do
+    test -z "$ac_dir" && ac_dir=.
+    if test -f $ac_dir/$ac_word; then
+      ac_cv_prog_latex2png="$ac_prog"
+      break
+    fi
+  done
+  IFS="$ac_save_ifs"
+fi
+fi
+latex2png="$ac_cv_prog_latex2png"
+if test -n "$latex2png"; then
+  echo "$ac_t""$latex2png" 1>&6
+else
+  echo "$ac_t""no" 1>&6
+fi
+
+test -n "$latex2png" && break
+done
+test -n "$latex2png" || latex2png="no"
+
+if test $latex2png = "no" ;
+then
+        { echo "configure: error: "You need the latex2png program to build the documentation. It is available at http://sourceforge.net/projects/latex2rtf/"" 1>&2; exit 1; }
+fi
+
+
+
+for ac_prog in latex
+do
+# Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
+echo "configure:1606: checking for $ac_word" >&5
+if eval "test \"`echo '$''{'ac_cv_prog_latex'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  if test -n "$latex"; then
+  ac_cv_prog_latex="$latex" # Let the user override the test.
+else
+  IFS="${IFS= 	}"; ac_save_ifs="$IFS"; IFS=":"
+  ac_dummy="$PATH"
+  for ac_dir in $ac_dummy; do
+    test -z "$ac_dir" && ac_dir=.
+    if test -f $ac_dir/$ac_word; then
+      ac_cv_prog_latex="$ac_prog"
+      break
+    fi
+  done
+  IFS="$ac_save_ifs"
+fi
+fi
+latex="$ac_cv_prog_latex"
+if test -n "$latex"; then
+  echo "$ac_t""$latex" 1>&6
+else
+  echo "$ac_t""no" 1>&6
+fi
+
+test -n "$latex" && break
+done
+test -n "$latex" || latex="no"
+
+if test $latex = "no" ;
+then
+        { echo "configure: error: "You need LaTeX to build the documentation. It is available at http://www.latex-project.org/"" 1>&2; exit 1; }
+fi
+
+
+
+for ac_prog in pnmtopng
+do
+# Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
+echo "configure:1648: checking for $ac_word" >&5
+if eval "test \"`echo '$''{'ac_cv_prog_pnmtopng'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  if test -n "$pnmtopng"; then
+  ac_cv_prog_pnmtopng="$pnmtopng" # Let the user override the test.
+else
+  IFS="${IFS= 	}"; ac_save_ifs="$IFS"; IFS=":"
+  ac_dummy="$PATH"
+  for ac_dir in $ac_dummy; do
+    test -z "$ac_dir" && ac_dir=.
+    if test -f $ac_dir/$ac_word; then
+      ac_cv_prog_pnmtopng="$ac_prog"
+      break
+    fi
+  done
+  IFS="$ac_save_ifs"
+fi
+fi
+pnmtopng="$ac_cv_prog_pnmtopng"
+if test -n "$pnmtopng"; then
+  echo "$ac_t""$pnmtopng" 1>&6
+else
+  echo "$ac_t""no" 1>&6
+fi
+
+test -n "$pnmtopng" && break
+done
+test -n "$pnmtopng" || pnmtopng="no"
+
+if test $pnmtopng = "no" ;
+then
+        { echo "configure: error: "You need the pnmtopng program included in the netpbm package. It is available at http://netpbm.sourceforge.net/"" 1>&2; exit 1; }
+fi
+
+
 echo $ac_n "checking for --with-java-bin""... $ac_c" 1>&6
-echo "configure:1559: checking for --with-java-bin" >&5
+echo "configure:1685: checking for --with-java-bin" >&5
 # Check whether --with-java-bin or --without-java-bin was given.
 if test "${with_java_bin+set}" = set; then
   withval="$with_java_bin"
@@ -1582,7 +1708,7 @@ oz_path_save=$PATH
     if test -z "$WITH_GLOBAL_OZ"; then
       
   echo $ac_n "checking for --with-global-oz""... $ac_c" 1>&6
-echo "configure:1586: checking for --with-global-oz" >&5
+echo "configure:1712: checking for --with-global-oz" >&5
   # Check whether --with-global-oz or --without-global-oz was given.
 if test "${with_global_oz+set}" = set; then
   withval="$with_global_oz"
@@ -1616,7 +1742,7 @@ fi
     # Extract the first word of "java", so it can be a program name with args.
 set dummy java; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:1620: checking for $ac_word" >&5
+echo "configure:1746: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_JAVA'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1663,7 +1789,7 @@ if test -n "$JAVA"; then
     if test -z "$WITH_GLOBAL_OZ"; then
       
   echo $ac_n "checking for --with-global-oz""... $ac_c" 1>&6
-echo "configure:1667: checking for --with-global-oz" >&5
+echo "configure:1793: checking for --with-global-oz" >&5
   # Check whether --with-global-oz or --without-global-oz was given.
 if test "${with_global_oz+set}" = set; then
   withval="$with_global_oz"
@@ -1697,7 +1823,7 @@ fi
     # Extract the first word of "javac", so it can be a program name with args.
 set dummy javac; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:1701: checking for $ac_word" >&5
+echo "configure:1827: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_JAVAC'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1743,7 +1869,7 @@ fi
     if test -z "$WITH_GLOBAL_OZ"; then
       
   echo $ac_n "checking for --with-global-oz""... $ac_c" 1>&6
-echo "configure:1747: checking for --with-global-oz" >&5
+echo "configure:1873: checking for --with-global-oz" >&5
   # Check whether --with-global-oz or --without-global-oz was given.
 if test "${with_global_oz+set}" = set; then
   withval="$with_global_oz"
@@ -1777,7 +1903,7 @@ fi
     # Extract the first word of "jar", so it can be a program name with args.
 set dummy jar; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:1781: checking for $ac_word" >&5
+echo "configure:1907: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_JAR'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1820,14 +1946,14 @@ fi
     fi
     
   echo $ac_n "checking for class path option""... $ac_c" 1>&6
-echo "configure:1824: checking for class path option" >&5
+echo "configure:1950: checking for class path option" >&5
   case `$JAVA -version 2>&1` in
   Kaffe*) JAVACP=-addclasspath;;
   *) JAVACP=-classpath;;
   esac
   echo "$ac_t""$JAVACP" 1>&6
   echo $ac_n "checking for --with-java-threads""... $ac_c" 1>&6
-echo "configure:1831: checking for --with-java-threads" >&5
+echo "configure:1957: checking for --with-java-threads" >&5
   # Check whether --with-java-threads or --without-java-threads was given.
 if test "${with_java_threads+set}" = set; then
   withval="$with_java_threads"
@@ -1846,7 +1972,7 @@ PATH=$oz_path_save
 
 
 echo $ac_n "checking for --with-documents""... $ac_c" 1>&6
-echo "configure:1850: checking for --with-documents" >&5
+echo "configure:1976: checking for --with-documents" >&5
 # Check whether --with-documents or --without-documents was given.
 if test "${with_documents+set}" = set; then
   withval="$with_documents"
@@ -1864,7 +1990,7 @@ DOC_DIRS=$oz_doc_dirs
 
 
 echo $ac_n "checking for --enable-chm""... $ac_c" 1>&6
-echo "configure:1868: checking for --enable-chm" >&5
+echo "configure:1994: checking for --enable-chm" >&5
 # Check whether --enable-chm or --disable-chm was given.
 if test "${enable_chm+set}" = set; then
   enableval="$enable_chm"
@@ -1885,7 +2011,7 @@ fi
 
 
 echo $ac_n "checking for --with-ozhome""... $ac_c" 1>&6
-echo "configure:1889: checking for --with-ozhome" >&5
+echo "configure:2015: checking for --with-ozhome" >&5
 # Check whether --with-ozhome or --without-ozhome was given.
 if test "${with_ozhome+set}" = set; then
   withval="$with_ozhome"
@@ -2080,6 +2206,9 @@ s%@OZENGINE@%$OZENGINE%g
 s%@THEEMACS@%$THEEMACS%g
 s%@EMACS_OPTIONS@%$EMACS_OPTIONS%g
 s%@OZDOC@%$OZDOC%g
+s%@latex2png@%$latex2png%g
+s%@latex@%$latex%g
+s%@pnmtopng@%$pnmtopng%g
 s%@JAVA_BIN@%$JAVA_BIN%g
 s%@JAVA@%$JAVA%g
 s%@JAVAC@%$JAVAC%g
@@ -2295,7 +2424,7 @@ if test "$no_recursion" != yes; then
       fi
     fi
 
-    cd "$ac_popdir"
+    cd $ac_popdir
   done
 fi
 
