* Deleted old cardVal and cardInt propagators.     * Added a macro to test if nsgmls is installed to build the docs.     * Added GeSetVarDist.oz
git-svn-id: https://gforge.info.ucl.ac.be/svn/mozart@17067 ada56829-ad1f-0410-b00f-83cda6628aec

diff --git a/mozart/doc/configure b/mozart/doc/configure
--- a/mozart/doc/configure
+++ b/mozart/doc/configure
@@ -1680,8 +1680,50 @@ then
 fi
 
 
+
+for ac_prog in nsgmls
+do
+# Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
+echo "configure:1690: checking for $ac_word" >&5
+if eval "test \"`echo '$''{'ac_cv_prog_nsgmls'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  if test -n "$nsgmls"; then
+  ac_cv_prog_nsgmls="$nsgmls" # Let the user override the test.
+else
+  IFS="${IFS= 	}"; ac_save_ifs="$IFS"; IFS=":"
+  ac_dummy="$PATH"
+  for ac_dir in $ac_dummy; do
+    test -z "$ac_dir" && ac_dir=.
+    if test -f $ac_dir/$ac_word; then
+      ac_cv_prog_nsgmls="$ac_prog"
+      break
+    fi
+  done
+  IFS="$ac_save_ifs"
+fi
+fi
+nsgmls="$ac_cv_prog_nsgmls"
+if test -n "$nsgmls"; then
+  echo "$ac_t""$nsgmls" 1>&6
+else
+  echo "$ac_t""no" 1>&6
+fi
+
+test -n "$nsgmls" && break
+done
+test -n "$nsgmls" || nsgmls="no"
+
+if test $nsgmls = "no" ;
+then
+        { echo "configure: error: "You need the nsgmls program included in the jade package. It is available at http://www.jclark.com/jade/"" 1>&2; exit 1; }
+fi
+
+
 echo $ac_n "checking for --with-java-bin""... $ac_c" 1>&6
-echo "configure:1685: checking for --with-java-bin" >&5
+echo "configure:1727: checking for --with-java-bin" >&5
 # Check whether --with-java-bin or --without-java-bin was given.
 if test "${with_java_bin+set}" = set; then
   withval="$with_java_bin"
@@ -1708,7 +1750,7 @@ oz_path_save=$PATH
     if test -z "$WITH_GLOBAL_OZ"; then
       
   echo $ac_n "checking for --with-global-oz""... $ac_c" 1>&6
-echo "configure:1712: checking for --with-global-oz" >&5
+echo "configure:1754: checking for --with-global-oz" >&5
   # Check whether --with-global-oz or --without-global-oz was given.
 if test "${with_global_oz+set}" = set; then
   withval="$with_global_oz"
@@ -1742,7 +1784,7 @@ fi
     # Extract the first word of "java", so it can be a program name with args.
 set dummy java; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:1746: checking for $ac_word" >&5
+echo "configure:1788: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_JAVA'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1789,7 +1831,7 @@ if test -n "$JAVA"; then
     if test -z "$WITH_GLOBAL_OZ"; then
       
   echo $ac_n "checking for --with-global-oz""... $ac_c" 1>&6
-echo "configure:1793: checking for --with-global-oz" >&5
+echo "configure:1835: checking for --with-global-oz" >&5
   # Check whether --with-global-oz or --without-global-oz was given.
 if test "${with_global_oz+set}" = set; then
   withval="$with_global_oz"
@@ -1823,7 +1865,7 @@ fi
     # Extract the first word of "javac", so it can be a program name with args.
 set dummy javac; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:1827: checking for $ac_word" >&5
+echo "configure:1869: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_JAVAC'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1869,7 +1911,7 @@ fi
     if test -z "$WITH_GLOBAL_OZ"; then
       
   echo $ac_n "checking for --with-global-oz""... $ac_c" 1>&6
-echo "configure:1873: checking for --with-global-oz" >&5
+echo "configure:1915: checking for --with-global-oz" >&5
   # Check whether --with-global-oz or --without-global-oz was given.
 if test "${with_global_oz+set}" = set; then
   withval="$with_global_oz"
@@ -1903,7 +1945,7 @@ fi
     # Extract the first word of "jar", so it can be a program name with args.
 set dummy jar; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:1907: checking for $ac_word" >&5
+echo "configure:1949: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_JAR'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1946,14 +1988,14 @@ fi
     fi
     
   echo $ac_n "checking for class path option""... $ac_c" 1>&6
-echo "configure:1950: checking for class path option" >&5
+echo "configure:1992: checking for class path option" >&5
   case `$JAVA -version 2>&1` in
   Kaffe*) JAVACP=-addclasspath;;
   *) JAVACP=-classpath;;
   esac
   echo "$ac_t""$JAVACP" 1>&6
   echo $ac_n "checking for --with-java-threads""... $ac_c" 1>&6
-echo "configure:1957: checking for --with-java-threads" >&5
+echo "configure:1999: checking for --with-java-threads" >&5
   # Check whether --with-java-threads or --without-java-threads was given.
 if test "${with_java_threads+set}" = set; then
   withval="$with_java_threads"
@@ -1972,7 +2014,7 @@ PATH=$oz_path_save
 
 
 echo $ac_n "checking for --with-documents""... $ac_c" 1>&6
-echo "configure:1976: checking for --with-documents" >&5
+echo "configure:2018: checking for --with-documents" >&5
 # Check whether --with-documents or --without-documents was given.
 if test "${with_documents+set}" = set; then
   withval="$with_documents"
@@ -1990,7 +2032,7 @@ DOC_DIRS=$oz_doc_dirs
 
 
 echo $ac_n "checking for --enable-chm""... $ac_c" 1>&6
-echo "configure:1994: checking for --enable-chm" >&5
+echo "configure:2036: checking for --enable-chm" >&5
 # Check whether --enable-chm or --disable-chm was given.
 if test "${enable_chm+set}" = set; then
   enableval="$enable_chm"
@@ -2011,7 +2053,7 @@ fi
 
 
 echo $ac_n "checking for --with-ozhome""... $ac_c" 1>&6
-echo "configure:2015: checking for --with-ozhome" >&5
+echo "configure:2057: checking for --with-ozhome" >&5
 # Check whether --with-ozhome or --without-ozhome was given.
 if test "${with_ozhome+set}" = set; then
   withval="$with_ozhome"
@@ -2209,6 +2251,7 @@ s%@OZDOC@%$OZDOC%g
 s%@latex2png@%$latex2png%g
 s%@latex@%$latex%g
 s%@pnmtopng@%$pnmtopng%g
+s%@nsgmls@%$nsgmls%g
 s%@JAVA_BIN@%$JAVA_BIN%g
 s%@JAVA@%$JAVA%g
 s%@JAVAC@%$JAVAC%g
