Windows

diff --git a/platform/configure b/platform/configure
--- a/platform/configure
+++ b/platform/configure
@@ -879,6 +879,19 @@ else
 fi
 
 
+case "$target" in
+   NONE)
+   ;;
+   i386-mingw32)
+    PLATFORMDIRS="mswindows $PLATFORMDIRS"
+    ;;
+
+   *) { echo "configure: error: "can only cross-compile for target i386-mingw32 not for $target"" 1>&2; exit 1; }
+    ;;
+esac
+
+
+
 subdirs="$PLATFORMDIRS"
 
 trap '' 1 2 15
