added some magic to make it work on windows for ozengine not it the PATH - i.e. so emulator.dll can be found
git-svn-id: https://gforge.info.ucl.ac.be/svn/mozart@15751 ada56829-ad1f-0410-b00f-83cda6628aec

diff --git a/trunk/mozart-stdlib/configure b/trunk/mozart-stdlib/configure
--- a/trunk/mozart-stdlib/configure
+++ b/trunk/mozart-stdlib/configure
@@ -620,6 +620,51 @@ if test "$VAR_OZE" = "UNDEFINED"; then
     { echo "configure: error: ozengine not found" 1>&2; exit 1; }
 fi
 
+for ac_prog in oztool oztool.exe
+do
+# Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
+echo "configure:629: checking for $ac_word" >&5
+if eval "test \"`echo '$''{'ac_cv_path_VAR_OZTOOL'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  case "$VAR_OZTOOL" in
+  /*)
+  ac_cv_path_VAR_OZTOOL="$VAR_OZTOOL" # Let the user override the test with a path.
+  ;;
+  ?:/*)			 
+  ac_cv_path_VAR_OZTOOL="$VAR_OZTOOL" # Let the user override the test with a dos path.
+  ;;
+  *)
+  IFS="${IFS= 	}"; ac_save_ifs="$IFS"; IFS=":"
+  ac_dummy="$prefix/bin:$PATH"
+  for ac_dir in $ac_dummy; do 
+    test -z "$ac_dir" && ac_dir=.
+    if test -f $ac_dir/$ac_word; then
+      ac_cv_path_VAR_OZTOOL="$ac_dir/$ac_word"
+      break
+    fi
+  done
+  IFS="$ac_save_ifs"
+  ;;
+esac
+fi
+VAR_OZTOOL="$ac_cv_path_VAR_OZTOOL"
+if test -n "$VAR_OZTOOL"; then
+  echo "$ac_t""$VAR_OZTOOL" 1>&6
+else
+  echo "$ac_t""no" 1>&6
+fi
+
+test -n "$VAR_OZTOOL" && break
+done
+test -n "$VAR_OZTOOL" || VAR_OZTOOL="UNDEFINED"
+
+if test "$VAR_OZTOOL" = "UNDEFINED"; then
+    { echo "configure: error: oztool not found" 1>&2; exit 1; }
+fi
+
 subdirs="ozmake"
 
 trap '' 1 2 15
@@ -769,6 +814,7 @@ s%@mandir@%$mandir%g
 s%@SET_MAKE@%$SET_MAKE%g
 s%@BUILDDIR@%$BUILDDIR%g
 s%@VAR_OZE@%$VAR_OZE%g
+s%@VAR_OZTOOL@%$VAR_OZTOOL%g
 s%@subdirs@%$subdirs%g
 
 CEOF
