Check if glib and gtk are installed.

diff --git a/platform/gtk/configure b/platform/gtk/configure
--- a/platform/gtk/configure
+++ b/platform/gtk/configure
@@ -1991,8 +1991,11 @@ else
   echo "$ac_t""no" 1>&6
 fi
 
+if test -z $glibpath; then
+    { echo "configure: error: You need the glib library to enable GTK support. It can be found at http://www.gtk.org" 1>&2; exit 1; }
+fi
 echo $ac_n "checking for Glib compile flags""... $ac_c" 1>&6
-echo "configure:1996: checking for Glib compile flags" >&5
+echo "configure:1999: checking for Glib compile flags" >&5
 GLIB_CFLAGS=`$glibpath --cflags`
 GLIB_LIBS=`$glibpath --libs`
 CFLAGS="$CFLAGS $GLIB_CFLAGS"
@@ -2003,7 +2006,7 @@ echo "$ac_t""ok" 1>&6
 # Extract the first word of "gtk-config", so it can be a program name with args.
 set dummy gtk-config; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:2007: checking for $ac_word" >&5
+echo "configure:2010: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_gtkpath'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -2035,8 +2038,11 @@ else
   echo "$ac_t""no" 1>&6
 fi
 
+if test -z $gtkpath; then
+    { echo "configure: error: You need the GTK library to enable GTK support. It can be found at http://www.gtk.org" 1>&2; exit 1; }
+fi
 echo $ac_n "checking for Gtk compile flags""... $ac_c" 1>&6
-echo "configure:2040: checking for Gtk compile flags" >&5
+echo "configure:2046: checking for Gtk compile flags" >&5
 GTK_CFLAGS=`$gtkpath --cflags`
 GTK_LIBS=`$gtkpath --libs`
 GTK_HDRS=`$gtkpath --prefix`/include/gtk
