Solaris port on its way

diff --git a/share/bin/oz b/share/bin/oz
--- a/share/bin/oz
+++ b/share/bin/oz
@@ -16,14 +16,19 @@ then
   export OZHOME
 fi
 
-# determine machine architecture
-if [ ${OZARCH-xx} = xx ]
-then
-  if   [ -f /usr/bin/arch ]; then OZARCH=`/usr/bin/arch`
-  elif [ -f /bin/machine ]; then OZARCH=`/bin/machine`
-  else echo 1>&2 "error: cannot determine machine type"; exit 1
-  fi
-fi
+# determine machine architecture and OS version
+system="`/bin/uname -m` `/bin/uname -s` `/bin/uname -r`"
+
+case $system in
+   sun4*\ SunOS\ 4.1*) OZARCH=sun4
+   ;;
+   sun4*\ SunOS\ 5*)   OZARCH=sol2
+   ;;
+   RISC\ ULTRIX\ 4.*)  OZARCH=mips
+   ;;
+   *)  echo "Cannot determine machine type and OS version" 1>&2 ; exit 1
+esac
+
 export OZARCH
 #echo "OZARCH = $OZARCH"
 
