- uname might not only be in /bin and /usr/bin
- support for cygwin

diff --git a/share/bin/ozplatform b/share/bin/ozplatform
--- a/share/bin/ozplatform
+++ b/share/bin/ozplatform
@@ -3,7 +3,8 @@
 
 if [ -x /bin/uname ]; then UNAME=/bin/uname
 elif [ -x /usr/bin/uname ]; then UNAME=/usr/bin/uname
-else echo "Cannot find uname" 1>&2 ; exit 1
+else UNAME=uname
+     #echo "Cannot find uname" 1>&2 ; exit 1
 fi
 
 system="`$UNAME -m` `$UNAME -s` `$UNAME -r`"
@@ -41,6 +42,8 @@ case $system in
    *sparc*NetBSD*)      OZARCH=netbsd-sparc
    ;;
    *i386*NetBSD*)       OZARCH=netbsd-i486
+   ;;
+   *i586*CYGWIN*)       OZARCH=win32-i486
    ;;
    *)  echo "Cannot determine machine type and OS version for '$system'" 1>&2 ; exit 1
    ;;
