Wuff wuff

diff --git a/platform/wish/configure b/platform/wish/configure
--- a/platform/wish/configure
+++ b/platform/wish/configure
@@ -1574,9 +1574,9 @@ fi
 
 if test -n "${with_tcl}"
 then
-    oz_tcl_lib_dir=$with_tcl
-    oz_tcl_inc_dir=$with_tcl
-    oz_tcl_lib_tcl_dir=$with_tcl
+    oz_tcl_lib_dir=$with_tcl/lib
+    oz_tcl_inc_dir=$with_tcl/include
+    oz_tcl_lib_tcl_dir=$with_tcl/lib/tcl8.0
 fi
 
 # Check whether --with-tcl_lib or --without-tcl_lib was given.
@@ -1658,14 +1658,14 @@ fi
 
 
 LDFLAGS="-L$oz_tcl_lib_dir $LDFLAGS"
-echo $ac_n "checking for Tcl_Init in -ltcl""... $ac_c" 1>&6
-echo "configure:1663: checking for Tcl_Init in -ltcl" >&5
-ac_lib_var=`echo tcl'_'Tcl_Init | sed 'y%./+-%__p_%'`
+echo $ac_n "checking for Tcl_Init in -ltcl8.0""... $ac_c" 1>&6
+echo "configure:1663: checking for Tcl_Init in -ltcl8.0" >&5
+ac_lib_var=`echo tcl8.0'_'Tcl_Init | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   ac_save_LIBS="$LIBS"
-LIBS="-ltcl  $LIBS"
+LIBS="-ltcl8.0  $LIBS"
 cat > conftest.$ac_ext <<EOF
 #line 1671 "configure"
 #include "confdefs.h"
@@ -1693,6 +1693,51 @@ LIBS="$ac_save_LIBS"
 fi
 if eval "test \"`echo '$ac_cv_lib_'$ac_lib_var`\" = yes"; then
   echo "$ac_t""yes" 1>&6
+    ac_tr_lib=HAVE_LIB`echo tcl8.0 | sed -e 's/[^a-zA-Z0-9_]/_/g' \
+    -e 'y/abcdefghijklmnopqrstuvwxyz/ABCDEFGHIJKLMNOPQRSTUVWXYZ/'`
+  cat >> confdefs.h <<EOF
+#define $ac_tr_lib 1
+EOF
+
+  LIBS="-ltcl8.0 $LIBS"
+
+else
+  echo "$ac_t""no" 1>&6
+echo $ac_n "checking for Tcl_Init in -ltcl""... $ac_c" 1>&6
+echo "configure:1708: checking for Tcl_Init in -ltcl" >&5
+ac_lib_var=`echo tcl'_'Tcl_Init | sed 'y%./+-%__p_%'`
+if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  ac_save_LIBS="$LIBS"
+LIBS="-ltcl  $LIBS"
+cat > conftest.$ac_ext <<EOF
+#line 1716 "configure"
+#include "confdefs.h"
+/* Override any gcc2 internal prototype to avoid an error.  */
+/* We use char because int might match the return type of a gcc2
+    builtin and then its argument prototype would still apply.  */
+char Tcl_Init();
+
+int main() {
+Tcl_Init()
+; return 0; }
+EOF
+if { (eval echo configure:1727: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
+  rm -rf conftest*
+  eval "ac_cv_lib_$ac_lib_var=yes"
+else
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  rm -rf conftest*
+  eval "ac_cv_lib_$ac_lib_var=no"
+fi
+rm -f conftest*
+LIBS="$ac_save_LIBS"
+
+fi
+if eval "test \"`echo '$ac_cv_lib_'$ac_lib_var`\" = yes"; then
+  echo "$ac_t""yes" 1>&6
     ac_tr_lib=HAVE_LIB`echo tcl | sed -e 's/[^a-zA-Z0-9_]/_/g' \
     -e 'y/abcdefghijklmnopqrstuvwxyz/ABCDEFGHIJKLMNOPQRSTUVWXYZ/'`
   cat >> confdefs.h <<EOF
@@ -1703,14 +1748,19 @@ EOF
 
 else
   echo "$ac_t""no" 1>&6
-{ echo "configure: error: required lib "-ltcl" not found" 1>&2; exit 1; }
+{ echo "configure: error: required lib "-ltcl/tcl8.0" not found" 1>&2; exit 1; }
 fi
 
+fi
+
+
+#AC_CHECK_LIB(tcl, Tcl_Init, ,
+#       AC_MSG_ERROR(required lib "-ltcl" not found))
 
 
 
 echo $ac_n "checking for --with-tk""... $ac_c" 1>&6
-echo "configure:1714: checking for --with-tk" >&5
+echo "configure:1764: checking for --with-tk" >&5
 # Check whether --with-tk or --without-tk was given.
 if test "${with_tk+set}" = set; then
   withval="$with_tk"
@@ -1719,9 +1769,9 @@ fi
 
 if test -n "${with_tk}"
 then
-    oz_tk_lib_dir=$with_tk
-    oz_tk_inc_dir=$with_tk
-    oz_tk_lib_tcl_dir=$with_tk
+    oz_tk_lib_dir=$with_tk/lib
+    oz_tk_inc_dir=$with_tk/include
+    oz_tk_lib_tcl_dir=$with_tk/lib/tk8.0
 fi
 
 # Check whether --with-tk_lib or --without-tk_lib was given.
@@ -1769,17 +1819,17 @@ echo "$ac_t""trying \"-L$oz_tk_lib_dir -I$oz_tk_inc_dir\"" 1>&6
 CPPFLAGS="-I$oz_tk_inc_dir $CPPFLAGS"
 ac_safe=`echo "tk.h" | sed 'y%./+-%__p_%'`
 echo $ac_n "checking for tk.h""... $ac_c" 1>&6
-echo "configure:1773: checking for tk.h" >&5
+echo "configure:1823: checking for tk.h" >&5
 if eval "test \"`echo '$''{'ac_cv_header_$ac_safe'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1778 "configure"
+#line 1828 "configure"
 #include "confdefs.h"
 #include <tk.h>
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:1783: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:1833: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out`
 if test -z "$ac_err"; then
   rm -rf conftest*
@@ -1803,16 +1853,16 @@ fi
 
 
 LDFLAGS="-L$oz_tk_lib_dir $LDFLAGS"
-echo $ac_n "checking for Tk_Init in -ltk""... $ac_c" 1>&6
-echo "configure:1808: checking for Tk_Init in -ltk" >&5
-ac_lib_var=`echo tk'_'Tk_Init | sed 'y%./+-%__p_%'`
+echo $ac_n "checking for Tk_Init in -ltk8.0""... $ac_c" 1>&6
+echo "configure:1858: checking for Tk_Init in -ltk8.0" >&5
+ac_lib_var=`echo tk8.0'_'Tk_Init | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   ac_save_LIBS="$LIBS"
-LIBS="-ltk  $LIBS"
+LIBS="-ltk8.0  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 1816 "configure"
+#line 1866 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
@@ -1823,7 +1873,52 @@ int main() {
 Tk_Init()
 ; return 0; }
 EOF
-if { (eval echo configure:1827: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
+if { (eval echo configure:1877: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
+  rm -rf conftest*
+  eval "ac_cv_lib_$ac_lib_var=yes"
+else
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  rm -rf conftest*
+  eval "ac_cv_lib_$ac_lib_var=no"
+fi
+rm -f conftest*
+LIBS="$ac_save_LIBS"
+
+fi
+if eval "test \"`echo '$ac_cv_lib_'$ac_lib_var`\" = yes"; then
+  echo "$ac_t""yes" 1>&6
+    ac_tr_lib=HAVE_LIB`echo tk8.0 | sed -e 's/[^a-zA-Z0-9_]/_/g' \
+    -e 'y/abcdefghijklmnopqrstuvwxyz/ABCDEFGHIJKLMNOPQRSTUVWXYZ/'`
+  cat >> confdefs.h <<EOF
+#define $ac_tr_lib 1
+EOF
+
+  LIBS="-ltk8.0 $LIBS"
+
+else
+  echo "$ac_t""no" 1>&6
+echo $ac_n "checking for Tk_Init in -ltk""... $ac_c" 1>&6
+echo "configure:1903: checking for Tk_Init in -ltk" >&5
+ac_lib_var=`echo tk'_'Tk_Init | sed 'y%./+-%__p_%'`
+if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  ac_save_LIBS="$LIBS"
+LIBS="-ltk  $LIBS"
+cat > conftest.$ac_ext <<EOF
+#line 1911 "configure"
+#include "confdefs.h"
+/* Override any gcc2 internal prototype to avoid an error.  */
+/* We use char because int might match the return type of a gcc2
+    builtin and then its argument prototype would still apply.  */
+char Tk_Init();
+
+int main() {
+Tk_Init()
+; return 0; }
+EOF
+if { (eval echo configure:1922: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -1848,7 +1943,9 @@ EOF
 
 else
   echo "$ac_t""no" 1>&6
-{ echo "configure: error: required lib "-ltk" not found" 1>&2; exit 1; }
+{ echo "configure: error: required lib "-ltk/tk8.0" not found" 1>&2; exit 1; }
+fi
+
 fi
 
 
@@ -1863,7 +1960,7 @@ fi
 
 
 echo $ac_n "checking whether to copy tcl libraries""... $ac_c" 1>&6
-echo "configure:1867: checking whether to copy tcl libraries" >&5
+echo "configure:1964: checking whether to copy tcl libraries" >&5
 
 if test "${enable_copy_tcl_libs}" = yes; then
    echo "$ac_t""yes" 1>&6
