PerdioVar now use ExtVar's, which means that they need no additional hooks in the emulator. Makefile/configure:   oztool.sh is not longer removed in 'make veryclean'   use oztool instead of ozdynld   --enable-gccld removed oztool: folded ozdynld
git-svn-id: https://gforge.info.ucl.ac.be/svn/mozart@8073 ada56829-ad1f-0410-b00f-83cda6628aec

diff --git a/trunk/mozart/platform/emulator/oztool.in b/trunk/mozart/platform/emulator/oztool.in
--- a/trunk/mozart/platform/emulator/oztool.in
+++ b/trunk/mozart/platform/emulator/oztool.in
@@ -9,15 +9,47 @@
 
 : ${oztool_cxx="@OZTOOL_CXX@"}
 : ${oztool_cc="cc"}
-: ${oztool_ld="$OZDYNLD"}
-
+: ${oztool_ld=$oztool_cxx}
 cmd=$1
 shift
 
 case "$cmd" in
-  c++) cmd=$oztool_cxx ;;
-  cc ) cmd=$oztool_cc  ;;
-  ld ) cmd=$oztool_ld  ;;
+  c++) cmd=$oztool_cxx;;
+  cc ) cmd=$oztool_cc;;
+  ld ) 
+    if [ -x /bin/uname ]; then uname=/bin/uname
+    elif [ -x /usr/bin/uname ]; then uname=/usr/bin/uname
+    else echo "Cannot find uname" 1>&2 ; exit 1
+    fi
+
+    system="`$uname -s`_`$uname -r`"
+
+    case $system in
+	SunOS_4.1*)
+	    cmd="$oztool_ld"
+	    ;;
+	SunOS_5*)
+	    cmd="$oztool_ld -Wl,-G"
+	    ;;
+	Linux_*)
+	    cmd="$oztool_ld -Wl,-shared"
+	    ;;
+	HP-UX_*)
+	    cmd="$oztool_ld -Wl,-b"
+	    ;;
+	IRIX_5*)
+	    cmd="$oztool_ld -Wl,-shared -Wl,-check_registry -Wl,/dev/null"
+	    ;;
+	OSF1_*)
+	    cmd="$oztool_ld -Wl,-shared -Wl,-expect_unresolved -Wl,'*'"
+	    ;;
+	FreeBSD_*|NetBSD_*)
+	    cmd="$oztool_ld -Wl,-Bshareable"
+	    ;;
+	*)
+	    echo "$0: platform $system not supported"
+	    exit 1
+	esac
   *  )
   echo "oztool: unknown command $cmd" 1>&2
   exit 1
