- version check for GTK+ - minor bug fixes
git-svn-id: https://gforge.info.ucl.ac.be/svn/mozart@12866 ada56829-ad1f-0410-b00f-83cda6628aec

diff --git a/trunk/mozart/platform/gtk/configure b/trunk/mozart/platform/gtk/configure
--- a/trunk/mozart/platform/gtk/configure
+++ b/trunk/mozart/platform/gtk/configure
@@ -2039,10 +2039,20 @@ else
 fi
 
 if test -z $gtkpath; then
-    { echo "configure: error: You need the GTK library to enable GTK support. It can be found at http://www.gtk.org" 1>&2; exit 1; }
+    { echo "configure: error: The gtk-config script" 1>&2; exit 1; }
 fi
-echo $ac_n "checking for GTK compile flags""... $ac_c" 1>&6
-echo "configure:2046: checking for GTK compile flags" >&5
+
+echo $ac_n "checking for GTK+ version""... $ac_c" 1>&6
+echo "configure:2047: checking for GTK+ version" >&5
+GTK_VERSION=`$gtkpath --version`
+case $GTK_VERSION in
+    1.2.*) ;;
+    *)     { echo "configure: error: Your GTK+ library is too old" 1>&2; exit 1; }
+esac
+echo "$ac_t""ok" 1>&6
+
+echo $ac_n "checking for GTK+ compile flags""... $ac_c" 1>&6
+echo "configure:2056: checking for GTK+ compile flags" >&5
 GTK_CFLAGS=`$gtkpath --cflags`
 GTK_LIBS=`$gtkpath --libs`
 GTK_HDRS=`$gtkpath --prefix`/include/gtk
@@ -2059,7 +2069,7 @@ GLADE_FAIL="not found. Glade support will be disabled."
 # Extract the first word of "libglade-config", so it can be a program name with args.
 set dummy libglade-config; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:2063: checking for $ac_word" >&5
+echo "configure:2073: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_libglade_config'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
